name: Run tests
on: push

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  checks: write

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -qy cmake libgtest-dev ninja-build

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Run CMake
        run: cmake -B build -D WITH_TESTS=ON -G Ninja .

      - name: Build project
        run: ninja -C build

      - name: Run tests
        run: ninja -C build test

      - name: Upload test-results
        uses: actions/upload-artifact@v4.4.0
        with:
          path: build/test-results

  upload-test-report:
    name: Upload test report
    runs-on: ubuntu-latest

    steps:
      - name: Download test results
        uses: actions/download-artifact@v4.1.8
        with:
          name: test-results

      - name: Publish test results
        uses: mikepenz/action-junit-report@v4.3.1
